import { FastifyInstance } from 'fastify';
import admissionsRouter from './admissions.router';
import studentsRouter from './students.router';
import batchesRouter from './batches.router';
import enrollRouter from './enroll.router';
import attendanceRouter from './attendance.router';
import feesRouter from './fees.router';
import passportRouter from './passport.router';
import submissionsRouter from './submissions.router';
import certificatesRouter from './certificates.router';
import academyProjectsRouter from './academy-projects.router';
import internshipsRouter from './internships.router';
import placementsRouter from './placements.router';
import riskRouter from './risk.router';
import marketplaceRouter from './marketplace.router';
import eventsRouter from './events.router';
import referralsRouter from './referrals.router';
import walkInsRouter from './walk-ins.router';
import dynamicFormsRouter from './dynamic-forms.router';
import forumsRouter from './forums.router';
import leaderboardRouter from './leaderboard.router';
import jobsRouter from './jobs.router';
import analyticsRouter from './analytics.router';
import alumniRouter from './alumni.router';
import portfolioRouter from './portfolio.router';
import officeHoursRouter from './office-hours.router';
import lmsStudentRoutes from './lms-student.router';

export default async function academyModule(app: FastifyInstance) {
  await app.register(admissionsRouter);
  await app.register(studentsRouter);
  await app.register(batchesRouter);
  await app.register(enrollRouter);
  await app.register(feesRouter);
  await app.register(passportRouter);
  await app.register(submissionsRouter);
  await app.register(academyProjectsRouter);
  await app.register(internshipsRouter);
  await app.register(placementsRouter);
  await app.register(riskRouter);
  await app.register(marketplaceRouter);
  await app.register(eventsRouter);
  await app.register(referralsRouter);
  await app.register(walkInsRouter);
  await app.register(dynamicFormsRouter);
  await app.register(attendanceRouter, { prefix: '/attendance' });
  await app.register(officeHoursRouter, { prefix: '/office-hours' });
  await app.register(certificatesRouter, { prefix: '/certificates' });
  await app.register(forumsRouter, { prefix: '/forums' });
  await app.register(leaderboardRouter, { prefix: '/leaderboard' });
  await app.register(jobsRouter, { prefix: '/jobs' });
  await app.register(analyticsRouter, { prefix: '/analytics' });
  await app.register(alumniRouter, { prefix: '/alumni' });
  await app.register(referralsRouter, { prefix: '/referrals' });
  await app.register(portfolioRouter, { prefix: '/portfolio' });
  await app.register(lmsStudentRoutes);
}
