#!/usr/bin/expect -f

set timeout 30
set password "$env(VPS_PASSWORD)"
set host "root@72.61.231.187"

spawn ssh -o StrictHostKeyChecking=no -o PubkeyAuthentication=no $host

expect {
    "password:" { send "$password\r" }
}

expect "# " { send "nginx -t\r" }
expect "# " { send "ls -la /etc/nginx/sites-enabled/\r" }
expect "# " { send "cat /etc/nginx/sites-enabled/* | grep -A 20 -B 5 -i 'grekam.in'\r" }
expect "# " { send "exit\r" }
expect eof
