#!/usr/bin/expect -f

set timeout 30
set password "Photoshop09@"
set host "root@72.61.231.187"

spawn ssh -o StrictHostKeyChecking=no -o PubkeyAuthentication=no $host

expect {
    "password:" { send "$password\r" }
}

expect "# " { send "curl -I -L http://localhost:3000\r" }
expect "# " { send "curl -k -I -L https://grekam.in\r" }
expect "# " { send "curl -k -I -L https://garage.grekam.in\r" }
expect "# " { send "exit\r" }
expect eof
