#!/usr/bin/expect -f

set timeout 30
set password "Photoshop09@"
set host "root@72.61.231.187"

spawn ssh -o StrictHostKeyChecking=no -o PubkeyAuthentication=no $host

expect {
    "password:" { send "$password\r" }
}

expect "# " { send "PGPASSWORD='Photoshop09@' psql -h 127.0.0.1 -U postgres -p 5432 -d grekam_os -c '\\dt' | head -n 20\r" }
expect "# " { send "PGPASSWORD='Photoshop09@' psql -h 127.0.0.1 -U postgres -p 5434 -d grekam_os -c '\\dt' | head -n 20\r" }
expect "# " { send "exit\r" }
expect eof
