#!/usr/bin/expect -f
set timeout 60
set host "200.97.163.236"
set user "root"
set password "Photoshop09@"

spawn ssh -o StrictHostKeyChecking=no -o IdentitiesOnly=yes -o PubkeyAuthentication=no $user@$host

expect "password:"
send "$password\r"
expect "# "

send "PGPASSWORD='garage_pass_2026' psql -h localhost -U garage -d garage -c 'SELECT id, email, role, status, \"firstName\", \"lastName\" FROM users;'\r"
expect "# "

send "exit\r"
expect eof
