#!/usr/bin/expect -f

set timeout 30
set password "Photoshop09@"
set host "root@72.61.231.187"

spawn ssh -o StrictHostKeyChecking=no -o PubkeyAuthentication=no $host

expect {
    "password:" { send "$password\r" }
}

expect "# " { send "export PAGER=cat\r" }
expect "# " { send "PGPASSWORD='Photoshop09@' psql -h 127.0.0.1 -U postgres -d grekam_os -c \"select id, email, role, \\\"customRoleId\\\" from users where email='grekamvisuals@gmail.com';\"\r" }
expect "# " { send "PGPASSWORD='Photoshop09@' psql -h 127.0.0.1 -U postgres -d grekam_os -c \"select id, name, description from roles;\"\r" }
expect "# " { send "PGPASSWORD='Photoshop09@' psql -h 127.0.0.1 -U postgres -d grekam_os -c \"select * from permissions where \\\"roleId\\\" = (select \\\"customRoleId\\\" from users where email='grekamvisuals@gmail.com');\"\r" }
expect "# " { send "exit\r" }
expect eof
