#!/usr/bin/expect -f
set timeout 300
set script {
  cd /root/grekam-os
  echo "Current directory: $(pwd)"
  git pull
  pnpm i
  cd packages/db && npx prisma generate && npx prisma db push && cd ../..
  NODE_OPTIONS="--max-old-space-size=4096" pnpm build:all
  pm2 delete grekam-os-web || true
  export HOST=0.0.0.0 && pm2 start pnpm --name grekam-os-web --cwd /root/grekam-os/apps/web -- start
  pm2 restart grekam-os-api --update-env || true
  pm2 restart academy-web --update-env || true
  pm2 save
}
spawn ssh -o StrictHostKeyChecking=no -o PubkeyAuthentication=no root@72.61.231.187 $script
expect "assword:"
send "Photoshop09@\r"
expect eof
