import { prisma } from "@/lib/prisma"
import { notFound } from "next/navigation"

export const dynamic = 'force-dynamic'

export default async function CMSPublicPage(props: { params: Promise<{ slug: string }> }) {
  const params = await props.params;
  console.log("CMSPublicPage HIT WITH SLUG:", params.slug);
  const page = await prisma.landingPage.findUnique({
    where: { slug: params.slug },
    include: {
      sections: {
        orderBy: { sortOrder: 'asc' }
      }
    }
  })

  if (!page || !page.isActive) {
    notFound()
  }

  return (
    <main className="min-h-screen bg-slate-50 flex flex-col w-full overflow-x-hidden">
      {page.sections.map((section) => {
        const content = section.content as any
        
        // If it's a raw HTML section
        if (content && typeof content === 'object' && content.type === 'html' && content.html) {
          return (
            <div 
              key={section.id} 
              dangerouslySetInnerHTML={{ __html: content.html }} 
              className="w-full"
            />
          )
        }
        
        // If it's a JSON/Visual builder block
        if (content && typeof content === 'object' && content.type) {
          switch (content.type) {
            case 'HERO':
              return (
                <section key={section.id} className="w-full py-24 bg-gradient-to-b from-gray-900 to-gray-800 text-white flex flex-col items-center justify-center text-center px-4">
                  <h1 className="text-5xl md:text-6xl font-bold tracking-tight mb-6">{content.title || 'Hero Title'}</h1>
                  <p className="text-xl text-gray-300 max-w-2xl mb-8">This is an automated hero section placeholder based on the visual builder.</p>
                  <button className="bg-purple-600 hover:bg-purple-700 text-white px-8 py-3 rounded-full font-medium transition-colors">
                    Get Started
                  </button>
                </section>
              )
            case 'TEXT':
              return (
                <section key={section.id} className="w-full py-16 px-4 md:px-8 max-w-4xl mx-auto prose prose-lg">
                  <h2>{content.title || 'Rich Text Block'}</h2>
                  <p>Content goes here. This block was generated by the CMS visual builder and will be extended with rich text content mapping.</p>
                </section>
              )
            case 'IMAGE_GRID':
              return (
                <section key={section.id} className="w-full py-16 px-4 md:px-8 max-w-6xl mx-auto">
                  <h2 className="text-3xl font-bold mb-12 text-center">{content.title || 'Image Grid'}</h2>
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                    {[1, 2, 3].map(i => (
                      <div key={i} className="aspect-video bg-gray-200 rounded-2xl flex items-center justify-center text-gray-400">
                        Image {i}
                      </div>
                    ))}
                  </div>
                </section>
              )
            case 'PRICING':
              return (
                <section key={section.id} className="w-full py-24 px-4 bg-slate-50">
                  <div className="max-w-6xl mx-auto">
                    <h2 className="text-4xl font-bold text-center mb-16">{content.title || 'Pricing Plans'}</h2>
                    <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                      {['Basic', 'Pro', 'Enterprise'].map((plan, i) => (
                        <div key={plan} className={`bg-white rounded-3xl p-8 border ${i === 1 ? 'border-purple-500 shadow-xl relative' : 'border-gray-200 shadow-sm'}`}>
                          {i === 1 && <div className="absolute top-0 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-purple-500 text-white px-4 py-1 rounded-full text-sm font-medium">Most Popular</div>}
                          <h3 className="text-2xl font-bold mb-4">{plan}</h3>
                          <p className="text-4xl font-extrabold mb-8">${(i+1)*29}<span className="text-lg text-gray-500 font-normal">/mo</span></p>
                          <button className={`w-full py-3 rounded-xl font-medium ${i === 1 ? 'bg-purple-600 text-white hover:bg-purple-700' : 'bg-gray-100 text-gray-900 hover:bg-gray-200'} transition-colors`}>
                            Choose Plan
                          </button>
                        </div>
                      ))}
                    </div>
                  </div>
                </section>
              )
            default:
              // Fallback for unknown visual builder blocks
              return (
                <div key={section.id} className="w-full py-12 px-4 text-center border-y border-dashed border-gray-300 text-gray-500">
                  Placeholder for generic block: {content.type}
                </div>
              )
          }
        }
        
        return null
      })}
    </main>
  )
}
