import React from 'react';
import { Html, Head, Body, Container, Section, Text, Img, Preview, Tailwind } from '@react-email/components';

export function BaseTemplate({ previewText, children }: { previewText: string, children: React.ReactNode }) {
  return (
    <Html>
      <Head />
      <Preview>{previewText}</Preview>
      <Tailwind>
        <Body className="bg-[#050505] font-sans text-white my-0 mx-auto p-4">
          <Container className="bg-[#111111] border border-[#222] rounded-xl p-8 max-w-[600px] mt-8 mx-auto">
            <Section className="mb-8">
              {/* Fake logo since we don't have a hosted one yet */}
              <Text className="text-xl font-bold tracking-tight m-0 p-0 text-white">Grekam OS</Text>
              <div className="w-8 h-1 bg-blue-500 mt-2 rounded-full"></div>
            </Section>
            
            {children}
            
            <Section className="mt-12 pt-8 border-t border-[#222]">
              <Text className="text-[#666] text-xs leading-5">
                © {new Date().getFullYear()} Grekam Visuals. All rights reserved.<br />
                This is an automated message generated by the Grekam Autopilot Engine.
              </Text>
            </Section>
          </Container>
        </Body>
      </Tailwind>
    </Html>
  );
}
