import { FastifyInstance } from 'fastify';

export default async function aiRouter(app: FastifyInstance) {
  // POST /api/v1/cms/ai-generate
  app.post('/ai-generate', async (req, reply) => {
    const { prompt } = req.body as { prompt: string };

    // Simulate AI generation delay
    await new Promise(res => setTimeout(res, 1500));

    // MOCK RESPONSE: A beautiful Tailwind HTML hero section
    const generatedHtml = `<section class="relative bg-slate-900 overflow-hidden py-24">
  <!-- Dynamic Background Graphic -->
  <div class="absolute top-0 right-0 -translate-y-1/3 translate-x-1/3 w-[800px] h-[800px] bg-[#49ABC9] opacity-20 blur-[120px] rounded-full pointer-events-none"></div>
  
  <div class="max-w-6xl mx-auto px-6 relative z-10 flex flex-col items-center text-center">
    <div class="inline-flex items-center gap-2 px-4 py-2 bg-white/10 border border-white/20 rounded-full text-sm font-bold text-white mb-8">
      <span class="w-2 h-2 rounded-full bg-green-400 animate-pulse"></span> Generated by Grekam AI
    </div>
    
    <h1 class="text-5xl md:text-7xl font-black text-white mb-6 leading-tight">
      ${prompt.toUpperCase() || 'ELEVATE YOUR BRAND'}
    </h1>
    
    <p class="text-lg md:text-xl text-white/70 max-w-2xl mb-10">
      We build stunning, high-performance digital experiences that convert. Start your journey with our industry-leading solutions today.
    </p>
    
    <div class="flex items-center gap-4">
      <a href="/contact" class="px-8 py-4 bg-[#49ABC9] hover:bg-[#3d8fa8] text-white font-bold rounded-xl transition-all shadow-[0_0_20px_rgba(73,171,201,0.4)]">
        Get Started Now
      </a>
      <a href="/portfolio" class="px-8 py-4 bg-white/10 hover:bg-white/20 text-white font-bold rounded-xl border border-white/10 transition-all">
        View Our Work
      </a>
    </div>
  </div>
</section>`;

    return { 
      success: true, 
      data: { html: generatedHtml } 
    };
  });
}
